services:

    web:
        environment:
            SECRET_KEY: "1iyuwk-25_bqo_l%-t+v_5h5_hlfn8+&7=euwt1x#yt231&w56"
            DEBUG: "True"
            NAME: "accountability"
            USER: "postgres"
            PASSWORD: "postgres"
            HOST: "db"
            PORT: "5432"
        # restart: always
        command: python manage.py runserver 0.0.0.0:8000
        container_name: back
        build:
            context: ./accountability_project/
            dockerfile: Dockerfile
        volumes:
            # just means that changes done here (in source code/ in the host) are also instantly applied/persisted inside the container
            - ./accountability_project:/code/backend
        ports:
            - "8000:8000"
        
        depends_on:
            - db
        networks:
            - backend

    db:
        image: postgres:13
        container_name: db
        environment: 
            - POSTGRES_DB=accountability
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - APP_DB_USER=develop
            - APP_DB_PASS=develop
            - APP_DB_NAME=accountability
        volumes: 
            # persist the data locally
            - pg-data:/var/lib/postgresql/data/
            # copy the initialization scripts inside the container, to create table
            - ./db:/docker-entrypoint-initdb.d/
        ports:
            - "5433:5432"
        networks:
            - backend
            - db_admin

    pgadmin:  
        image: dpage/pgadmin4
        container_name: pg_admin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'  
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5051:80"
        networks:
            - db_admin

volumes: 
    pg-data:
        driver: local
    pgadmin:
        driver: local

networks:
    backend:
        driver: bridge
    db_admin:
        driver: bridge