# Generated by Django 3.1.13 on 2023-03-20 06:59

import Models.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210910_0732'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Models.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='bla_test',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bla_test',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
