# Generated by Django 3.1.13 on 2023-03-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230320_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='bla_test',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bla_test',
        ),
    ]
