# Generated by Django 3.1.13 on 2025-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20231115_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='avatar seed'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='avatar seed'),
        ),
    ]
