# Generated by Django 3.1.13 on 2025-03-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20250306_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
