# Generated by Django 5.2 on 2026-03-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_historicaluser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='UID provided by Firebase Authentication.', max_length=128, null=True, verbose_name='Firebase UID'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_anonymous_firebase_user',
            field=models.BooleanField(default=False, help_text='True when the user signed in anonymously via Firebase.'),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='UID provided by Firebase Authentication.', max_length=128, null=True, unique=True, verbose_name='Firebase UID'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_anonymous_firebase_user',
            field=models.BooleanField(default=False, help_text='True when the user signed in anonymously via Firebase.'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='username'),
        ),
    ]
