# Generated by Django 3.1.13 on 2021-11-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_basehabit_space'),
        ('spaces', '0003_auto_20211128_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacerole',
            name='space',
        ),
        migrations.RemoveField(
            model_name='spacerole',
            name='user',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
        migrations.DeleteModel(
            name='SpaceRole',
        ),
    ]
