# Generated by Django 3.1.13 on 2021-11-28 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0004_remove_basehabit_space'),
        ('spaces', '0004_auto_20211128_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_spaces', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='habits.HabitTag')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'db_table': 'space',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'admin'), ('member', 'member')], max_length=30)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Space Role',
                'verbose_name_plural': 'Space Roles',
                'db_table': 'role',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='space',
            name='users',
            field=models.ManyToManyField(related_name='user_spaces', through='spaces.SpaceRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
