# Generated by Django 3.1.13 on 2021-11-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_auto_20211128_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacerole',
            options={'ordering': ['role'], 'verbose_name': 'Space Role', 'verbose_name_plural': 'Space Roles'},
        ),
        migrations.RenameField(
            model_name='space',
            old_name='users',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='spacerole',
            old_name='user',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='spacerole',
            old_name='name',
            new_name='role',
        ),
        migrations.AlterModelTable(
            name='spacerole',
            table='space_role',
        ),
    ]
