# Generated by Django 3.1.13 on 2021-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_auto_20211128_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacerole',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member')], max_length=20),
        ),
    ]
