# Generated by Django 3.1.13 on 2021-12-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_auto_20211204_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacerole',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_roles', to='spaces.space'),
        ),
    ]
