# Generated by Django 3.1.13 on 2022-03-31 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_auto_20211204_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacerole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spacerole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
