# Generated by Django 3.1.13 on 2022-04-03 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0010_auto_20220331_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_spaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
