# Generated by Django 3.1.13 on 2023-11-15 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0011_auto_20220403_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacerole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaceusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
