# Generated by Django 3.1.13 on 2023-12-20 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0013_auto_20231116_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacerole',
            name='member',
            field=models.ForeignKey(help_text='PK of the user', on_delete=django.db.models.deletion.CASCADE, related_name='spaceroles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spacerole',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member')], help_text="Character field with the choices of 'admin' or 'member'", max_length=20),
        ),
        migrations.AlterField(
            model_name='spacerole',
            name='space',
            field=models.ForeignKey(help_text='PK of the space', on_delete=django.db.models.deletion.CASCADE, related_name='spaceroles', to='spaces.space'),
        ),
    ]
