# Generated by Django 3.1.13 on 2023-12-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0014_auto_20231220_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='icon_alias',
            field=models.CharField(blank=True, help_text='PK of the user', max_length=50, null=True),
        ),
    ]
