# Generated by Django 3.1.13 on 2023-12-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0015_space_icon_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='icon_alias',
            field=models.CharField(blank=True, help_text='the alias of the icon for this space, according to the frontend alias to icon mapper', max_length=50, null=True),
        ),
    ]
