# Generated by Django 4.2.20 on 2025-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0016_auto_20231224_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spacerole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
