# Generated by Django 3.1.13 on 2021-10-10 17:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(editable=False, max_length=11)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('space', models.ManyToManyField(blank=True, to='spaces.Space')),
            ],
        ),
        migrations.CreateModel(
            name='HabitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Habit Tag',
                'verbose_name_plural': 'Habit Tags',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('basehabit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.basehabit')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
            bases=('habits.basehabit',),
        ),
        migrations.CreateModel(
            name='RecurrentHabit',
            fields=[
                ('basehabit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.basehabit')),
                ('times', models.IntegerField()),
                ('time_frame', models.CharField(choices=[('W', 'Week'), ('M', 'Month')], max_length=1)),
            ],
            options={
                'verbose_name': 'Recurrent Habit',
                'verbose_name_plural': 'Recurrent Habits',
            },
            bases=('habits.basehabit',),
        ),
        migrations.CreateModel(
            name='CheckMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('satus', models.CharField(choices=[('UNDEFINED', 'undefined'), ('NOT_PLANNED', 'not planned'), ('DONE', 'done'), ('NOT_DONE', 'not done')], default='UNDEFINED', max_length=13)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.basehabit')),
            ],
            options={
                'verbose_name': 'Check Mark',
                'verbose_name_plural': 'Check Marks',
            },
        ),
        migrations.AddField(
            model_name='basehabit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='habits.HabitTag'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.goal')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
            },
        ),
    ]
