# Generated by Django 3.1.8 on 2021-09-07 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210907_1636'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='users.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('basehabit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.basehabit')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
            bases=('habits.basehabit',),
        ),
        migrations.CreateModel(
            name='RecurrentHabit',
            fields=[
                ('basehabit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.basehabit')),
                ('times', models.IntegerField()),
                ('time_frame', models.CharField(choices=[('W', 'Week'), ('M', 'Month')], max_length=1)),
            ],
            options={
                'verbose_name': 'Recurrent Habit',
                'verbose_name_plural': 'Recurrent Habits',
            },
            bases=('habits.basehabit',),
        ),
    ]
