# Generated by Django 3.1.7 on 2021-04-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StardDay',
            new_name='StartDay',
        ),
    ]
