# Generated by Django 3.1.13 on 2021-10-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkmark',
            options={'ordering': ['-date'], 'verbose_name': 'Check Mark', 'verbose_name_plural': 'Check Marks'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-date'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
    ]
