# Generated by Django 3.1.13 on 2021-10-23 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20211019_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basehabit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='recurrenthabit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recurrent Habit', 'verbose_name_plural': 'Recurrent Habits'},
        ),
        migrations.AddField(
            model_name='checkmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkmark',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkmarks', to='habits.basehabit'),
        ),
    ]
