# Generated by Django 3.1.8 on 2021-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('habits', '0002_auto_20210907_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehabit',
            name='space',
            field=models.ManyToManyField(blank=True, null=True, to='spaces.Space'),
        ),
    ]
