# Generated by Django 3.1.13 on 2021-11-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20211118_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basehabit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Habit', 'verbose_name_plural': 'Base Habits'},
        ),
        migrations.AlterModelOptions(
            name='habittag',
            options={'ordering': ['name'], 'verbose_name': 'Habit Tag', 'verbose_name_plural': 'Habit Tags'},
        ),
        migrations.AlterModelTable(
            name='basehabit',
            table='base_habit',
        ),
        migrations.AlterModelTable(
            name='checkmark',
            table='checkmark',
        ),
        migrations.AlterModelTable(
            name='goal',
            table='goal',
        ),
        migrations.AlterModelTable(
            name='habittag',
            table='habit_tag',
        ),
        migrations.AlterModelTable(
            name='milestone',
            table='milestone',
        ),
        migrations.AlterModelTable(
            name='recurrenthabit',
            table='recurrent_habit',
        ),
    ]
