# Generated by Django 3.1.8 on 2021-09-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        ('users', '0003_auto_20210910_0732'),
        ('habits', '0003_basehabit_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehabit',
            name='space',
            field=models.ManyToManyField(blank=True, to='spaces.Space'),
        ),
        migrations.AlterField(
            model_name='basehabit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='users.Tag'),
        ),
    ]
