# Generated by Django 3.1.13 on 2021-10-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20211023_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkmark',
            old_name='satus',
            new_name='status',
        ),
    ]
