# Generated by Django 3.1.13 on 2021-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_auto_20211128_1427'),
        ('habits', '0004_remove_basehabit_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='basehabit',
            name='space',
            field=models.ManyToManyField(blank=True, to='spaces.Space'),
        ),
    ]
