# Generated by Django 3.1.13 on 2021-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20211023_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('DONE', 'done'), ('NOT_DONE', 'not done')], default='NOT_DONE', max_length=13),
        ),
    ]
