# Generated by Django 3.1.13 on 2021-10-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='habits.goal'),
        ),
    ]
