# Generated by Django 3.1.8 on 2021-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='basehabit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='habits.HabitTag'),
        ),
    ]
