# Generated by Django 3.1.13 on 2021-10-29 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20211025_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmark',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
