# Generated by Django 3.1.13 on 2021-12-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_auto_20211204_1251'),
        ('habits', '0006_auto_20211204_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehabit',
            name='spaces',
            field=models.ManyToManyField(blank=True, related_name='habits', to='spaces.Space'),
        ),
    ]
