# Generated by Django 3.1.13 on 2022-03-31 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0010_auto_20220331_0614'),
        ('habits', '0007_auto_20211207_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehabit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basehabit',
            name='spaces',
            field=models.ManyToManyField(blank=True, related_name='space_habits', to='spaces.Space'),
        ),
    ]
