# Generated by Django 3.1.8 on 2021-10-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20210930_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkmark',
            options={'verbose_name': 'Check Mark', 'verbose_name_plural': 'Check Marks'},
        ),
        migrations.AlterModelOptions(
            name='habittag',
            options={'verbose_name': 'Habit Tag', 'verbose_name_plural': 'Habit Tags'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.CharField(default='goal', editable=False, max_length=11),
        ),
    ]
