# Generated by Django 3.1.13 on 2021-10-31 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20211029_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmark',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkmark',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkmarks', to='habits.basehabit', unique_for_date='date'),
        ),
    ]
