# Generated by Django 3.1.13 on 2021-10-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_auto_20211031_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmark',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkmarks', to='habits.basehabit'),
        ),
        migrations.AlterField(
            model_name='checkmark',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'undefined'), ('NOT_PLANNED', 'not planned'), ('DONE', 'done'), ('NOT_DONE', 'not done')], default='UNDEFINED', max_length=13, unique_for_date='date'),
        ),
    ]
