# Generated by Django 5.2 on 2025-08-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_alter_basehabit_id_alter_checkmark_id_and_more'),
        ('spaces', '0017_alter_space_id_alter_spacerole_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseHabitSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basehabit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.basehabit')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
            ],
        ),
        migrations.AddField(
            model_name='basehabit',
            name='spaces_new',
            field=models.ManyToManyField(blank=True, related_name='space_habits_new', through='habits.BaseHabitSpace', to='spaces.space'),
        ),
        migrations.AddConstraint(
            model_name='basehabitspace',
            constraint=models.UniqueConstraint(fields=('basehabit',), name='unique_basehabit_one_space'),
        ),
        migrations.AddConstraint(
            model_name='basehabitspace',
            constraint=models.UniqueConstraint(fields=('basehabit', 'space'), name='unique_basehabit_space_pair'),
        ),
    ]
