# Generated by Django 3.1.13 on 2021-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_auto_20211031_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmark',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'undefined'), ('NOT_PLANNED', 'not planned'), ('DONE', 'done'), ('NOT_DONE', 'not done')], default='UNDEFINED', max_length=13),
        ),
    ]
