# Generated by Django 3.1.13 on 2021-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_auto_20211031_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmark',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(),
        ),
    ]
