# Generated by Django 5.2 on 2025-08-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_basehabitspace_basehabit_spaces_new_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basehabitspace',
            table='space_habit',
        ),
    ]
