# Generated by Django 5.2 on 2025-08-22 20:46

from django.db import migrations

def copy_spaces_to_spaces_new(apps, schema_editor):
    """
    Copy data from the old spaces field to the new spaces_new field
    """
    BaseHabit = apps.get_model('habits', 'BaseHabit')
    BaseHabitSpace = apps.get_model('habits', 'BaseHabitSpace')
    
    for habit in BaseHabit.objects.all():
        # For each habit, get all its spaces from the old relationship
        for space in habit.spaces.all():
            # Create a through model instance for each relationship
            BaseHabitSpace.objects.create(basehabit=habit, space=space)

def reverse_migration(apps, schema_editor):
    """
    Reverse the migration if needed
    """
    # If you need to reverse, you might want to implement this
    # For now, we'll just pass as reversing might be complex
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_basehabitspace_table'),
    ]

    operations = [
        migrations.RunPython(copy_spaces_to_spaces_new, reverse_migration),
    ]
