# Generated by Django 3.1.13 on 2021-11-01 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_auto_20211031_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
