# Generated by Django 5.2 on 2025-08-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_auto_20250822_2046'),
        ('spaces', '0017_alter_space_id_alter_spacerole_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basehabit',
            name='spaces',
        ),
        migrations.RenameField(
            model_name='basehabit',
            old_name='spaces_new',
            new_name='spaces',
        ),
    ]
