# Generated by Django 5.2 on 2025-08-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_remove_basehabit_spaces_new_alter_basehabit_spaces'),
        ('spaces', '0017_alter_space_id_alter_spacerole_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehabit',
            name='spaces',
            field=models.ManyToManyField(blank=True, related_name='space_habits', through='habits.BaseHabitSpace', to='spaces.space'),
        ),
        migrations.AlterModelTable(
            name='basehabit',
            table='habit',
        ),
    ]
