# Generated by Django 5.2 on 2026-04-30 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_alter_basehabit_spaces_alter_basehabit_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXPLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_title_snap', models.CharField(blank=True, default='', max_length=100)),
                ('period_start', models.DateField(help_text='First day (Monday or 1st of month) of the completed period')),
                ('xp_awarded', models.PositiveIntegerField()),
                ('streak_at_award', models.PositiveIntegerField(default=0, help_text='Streak length (in periods) at the time of award')),
                ('multiplier', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('reason', models.CharField(choices=[('WEEKLY_HABIT', 'Weekly habit completion'), ('MONTHLY_HABIT', 'Monthly habit completion'), ('MILESTONE', 'Goal milestone reached')], max_length=15)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_entries', to='habits.basehabit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User XP Ledger Entry',
                'verbose_name_plural': 'User XP Ledger Entries',
                'db_table': 'user_xp_ledger',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('habit__isnull', False)), fields=('user', 'habit', 'period_start'), name='unique_xp_per_habit_per_period')],
            },
        ),
    ]
